# sshd on archlinux
#
# VERSION               0.0.1
 
FROM     base/archlinux:latest
MAINTAINER 	Bill Anderson <bill.anderson@rackspace.com>

ADD rids-api /usr/bin/
 
# Run daemon
CMD ["/usr/bin/rids-api"]
